module.exports = [
  {
    name: 'default',
    type: 'mysql',
    host: process.env.MYSQLHOST,
    port: process.env.MYSQLPORT,
    username: process.env.MYSQLUSER,
    password: process.env.MYSQLPW,
    database: process.env.MYSQLDB,
    synchronize: false,
    logging: true,
    entities: ['./dist/entities/MySQL/*.*'],
  },
  {
    name: 'pg',
    type: 'postgres',
    host: process.env.PGHOST,
    port: process.env.PGPORT,
    username: process.env.PGUSER,
    password: process.env.PGPW,
    database: process.env.PGDB,
    schema: 'public',
    synchronize: false,
    logging: true,
    entities: ['./dist/entities/PG/*.*'],
  },
];
