module.exports = [
  {
    name: 'default',
    type: 'mysql',
    host: 'localhost',
    port: 3306,
    username: 'root',
    password: 'root',
    database: 'app_development',
    synchronize: false,
    logging: true,
    entities: ['./src/entities/MySQL/*.*'],
  },
  {
    name: 'pg',
    type: 'postgres',
    host: 'localhost',
    port: 5432,
    username: 'william',
    password: 'root',
    database: 'dwh_development',
    schema: 'public',
    synchronize: false,
    logging: true,
    entities: ['./src/entities/PG/*.*'],
  },
];
